global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    file_sd_configs:
      - files:
        - /etc/prometheus/targets/cadvisor.json

  - job_name: 'node_exporter'
    file_sd_configs:
      - files:
          - /etc/prometheus/targets/node_exporter.json
