name: PACE Infrastructure Pipeline

on:
  workflow_dispatch:
    inputs:
      targetEnv:
        description: 'Environment to deploy to'
        type: choice
        required: true
        default: 'Development'
        options:
          - Development
          - Staging
          - Testing
          - Production
  push:
    branches:
      - master
      - dev
      - feature/*
      - upstream/*

defaults:
  run:
    shell: bash
    working-directory: ./infra-scripts

env:
  DOJO_PATH: ${{ github.workspace }}
  DATA_PATH: ${{ vars.DATA_PATH }}

  DOJO_HOST: ${{ vars.DOJO_HOST }}
  VIRTUAL_HOST: ${{ vars.DOJO_HOST }}
  LETSENCRYPT_HOST: ${{ vars.DOJO_HOST }}

  CTF_NAME: ${{ vars.CTF_NAME }}
  CTF_DESC: ""
  CTFD_WORKERS: ${{ vars.CTFD_WORKERS }}

jobs:
  # quick deploy dev
  refresh-dev:
    runs-on: [self-hosted, dev-runner]
    # If commit message pushed by dev1 to feature/* and upstream/* does NOT 
    # start with "DEPLOY:"
    if: |
      github.actor == vars.DEV1_SERVER_USER &&
      github.event_name == 'push' &&
      !startsWith(github.event.head_commit.message, 'DEPLOY:') &&
      (
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/upstream/')
      )
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Quick Deploy
        run: docker exec dojo dojo sync
    
  # quick deploy dev2 (tested)
  refresh-dev2:
    runs-on: [self-hosted, dev2-runner]
    # If commit message pushed by dev2 to feature/* and upstream/* does NOT 
    # start with "DEPLOY:"
    if: |
      github.actor == vars.DEV2_SERVER_USER &&
      github.event_name == 'push' &&
      !startsWith(github.event.head_commit.message, 'DEPLOY:') &&
      (
        startsWith(github.ref, 'refs/heads/feature/') ||
        startsWith(github.ref, 'refs/heads/upstream/')
      )
    environment: dev2
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Quick Deploy
        run: docker exec dojo dojo sync

  # Build Docker container
  build-dev:
    runs-on: [self-hosted, dev-runner]
    # Allow dev1 user to manually deploy any branch but only deploy 
    # feature/ and upstream/ via push and only if commit 
    # starts with "DEPLOY:"
    if: |
      github.actor == vars.DEV1_SERVER_USER &&
      (
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Development' 
        ) ||
        ( 
          startsWith(github.event.head_commit.message, 'DEPLOY:') &&
          (
            startsWith(github.ref, 'refs/heads/feature/') ||
            startsWith(github.ref, 'refs/heads/upstream/')
          )
        )
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Build Docker Image
        run: ./infra-build.sh

  build-dev2:
    runs-on: [self-hosted, dev2-runner]
    # Allow dev2 user to manually deploy any branch but only deploy 
    # feature/ and upstream/ via push and only if commit 
    # starts with "DEPLOY:"
    if: |
      github.actor == vars.DEV2_SERVER_USER &&
      (
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Development' 
        ) ||
        ( 
          startsWith(github.event.head_commit.message, 'DEPLOY:') &&
          (
            startsWith(github.ref, 'refs/heads/feature/') ||
            startsWith(github.ref, 'refs/heads/upstream/')
          )
        )
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Build Docker Image
        run: ./infra-build.sh

  build-staging:
    runs-on: [self-hosted, staging-runner]
    # Only allow dev branch
    # If manual deployment, ensure targetEnv is Staging
    if: |
      github.ref == 'refs/heads/dev' &&
      (
        github.event_name == 'push' ||
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Staging'
        )
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Build Docker Image
        run: ./infra-build.sh

  build-testing:
    runs-on: [self-hosted, testing-runner]
    # Only allow master branch
    # If manual deployment, ensure targetEnv is Testing
    if: |
      github.ref == 'refs/heads/master' &&
      (
        github.event_name == 'push' ||
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Testing'
        )
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Build Docker Image
        run: ./infra-build.sh
      
  build-prod:
    needs: deploy-testing
    runs-on: [self-hosted, prod-runner]
    # Only allow master branch
    # If manual deployment, ensure targetEnv is Production
    if: |
      github.ref == 'refs/heads/master' &&
      (
        github.event_name == 'push' ||
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Production'
        )
      )
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      
      - name: Build Docker Image
        run: ./infra-build.sh

  # Deploy to Dev (feature/* and upstream/* branches)
  deploy-dev:
    needs: build-dev
    # Allow dev1 user to manually deploy any branch but only deploy 
    # feature/ and upstream/ via push and only if commit 
    # starts with "DEPLOY:"
    if: |
      github.actor == vars.DEV1_SERVER_USER &&
      (
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Development' 
        ) ||
        ( 
          startsWith(github.event.head_commit.message, 'DEPLOY:') &&
          (
            startsWith(github.ref, 'refs/heads/feature/') ||
            startsWith(github.ref, 'refs/heads/upstream/')
          )
        )
      )
    runs-on: [self-hosted, dev-runner]
    environment: dev
    steps:
      - name: Stop and Remove Existing Container
        run: ./infra-down.sh
      
      - name: Run Docker Container
        run: ./infra-up.sh
        
  # Deploy to dev2 environment (feature/* and upstream/* branches)
  deploy-dev2:
    needs: build-dev2
    # Allow dev2 user to manually deploy any branch but only deploy 
    # feature/ and upstream/ via push and only if commit 
    # starts with "DEPLOY:"
    if: |
      github.actor == vars.DEV2_SERVER_USER &&
      (
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Development' 
        ) ||
        ( 
          startsWith(github.event.head_commit.message, 'DEPLOY:') &&
          (
            startsWith(github.ref, 'refs/heads/feature/') ||
            startsWith(github.ref, 'refs/heads/upstream/')
          )
        )
      )
    runs-on: [self-hosted, dev2-runner]
    environment: dev2
    steps:
      - name: Stop and Remove Existing Container
        run: ./infra-down.sh
      
      - name: Run Docker Container
        run: ./infra-up.sh

  # Deploy to Staging (dev branch)
  deploy-staging:
    needs: build-staging
    # Only allow dev branch
    # If manual deployment, ensure targetEnv is Staging
    if: |
      github.ref == 'refs/heads/dev' &&
      (
        github.event_name == 'push' ||
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Staging'
        )
      )
    runs-on: [self-hosted, staging-runner]
    environment: staging
    steps:
      - name: Stop and Remove Existing Container
        run: ./infra-down.sh
      
      - name: Run Docker Container
        run: ./infra-up.sh
      
  # Deploy to Testing (master branch)
  deploy-testing:
    needs: build-testing
    # Only allow master branch
    # If manual deployment, ensure targetEnv is Testing
    if: |
      github.ref == 'refs/heads/master' &&
      (
        github.event_name == 'push' ||
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Testing'
        )
      )
    runs-on: [self-hosted, testing-runner]
    environment: testing
    steps:
      - name: Stop and Remove Existing Container
        run: ./infra-down.sh
      
      - name: Run Docker Container
        run: ./infra-up.sh
    
  # Deploy to Production (master branch)
  deploy-prod:
    needs: build-prod
    # Only allow master branch
    # If manual deployment, ensure targetEnv is Production
    if: |
      github.ref == 'refs/heads/master' &&
      (
        github.event_name == 'push' ||
        (
          github.event_name == 'workflow_dispatch' &&
          github.event.inputs.targetEnv == 'Production'
        )
      )
    runs-on: [self-hosted, prod-runner]
    environment: production
    steps:
      - name: Stop and Remove Existing Container
        run: ./infra-down.sh
      
      - name: Run Docker Container
        run: ./infra-up.sh
